import type { MethodMatch, MoveLabelName, RegisterName, Script } from "@/lib/ai/schemas";

/** Shapes shared between server and client. Kept free of Prisma imports so
 *  client components can use them without pulling the engine into the bundle. */

export interface ProblemView {
  id: string;
  index: number;
  printedText: string;
  childWorkText: string | null;
  childAnswer: string | null;
  ocrConfidence: number | null;
  standardCode: string | null;
  /** How close the search that chose `standardCode` was, 0 to 1, or null for
   *  a problem matched before scores were recorded. */
  standardSimilarity: number | null;
  expectedMethod: string | null;
  verified: boolean;
  computedAnswer: string | null;
  misconceptionId: string | null;
  status: "OPEN" | "SOLVED" | "PARKED";
}

/**
 * Below this, the standard chip says "closest match" instead of asserting one.
 *
 * Chosen from what the corpus actually returns rather than from a round
 * number: a problem that is plainly about a seeded standard comes back in the
 * high 0.7s and above, and the tail below 0.6 is where the search is matching
 * on shape rather than on subject. It is a starting line, and it is stored
 * per problem so it can be moved without re-embedding anything.
 *
 * The distinction matters because the chip is a claim about a child's
 * classroom. "This is what your class is doing" and "this is the nearest
 * thing we found" are different sentences, and a product that only knows how
 * to say the first one says it when it is not true.
 */
export const STANDARD_CERTAIN_AT = 0.6;

/** True when the chip should hedge rather than assert. */
export function standardIsUncertain(similarity: number | null): boolean {
  // Null is a problem matched before scores were recorded. Not known is not
  // the same as low, and a backfilled hedge would be a guess on screen.
  return similarity !== null && similarity < STANDARD_CERTAIN_AT;
}

/**
 * A retrieval candidate: a standard, and how close it was.
 *
 * Separate from `StandardView` because most of the product holds a standard it
 * already knows is the right one. Similarity is a fact about a search, not
 * about a standard, and putting it on the shared type would mean every
 * `standardByCode` result carrying a number that means nothing.
 */
export interface StandardCandidate extends StandardView {
  /**
   * Cosine similarity to the problem text, from 0 to 1.
   *
   * pgvector's `<=>` returns cosine *distance*, so this is `1 - distance`,
   * clamped. Worth knowing when reading a low number: an embedding model puts
   * almost everything in a fairly narrow band, so 0.4 is not "40% right", it
   * is "further away than anything we would normally act on".
   */
  similarity: number;
}

export interface StandardView {
  code: string;
  /** CCSS, ENC or CBSE. Shown to the parent when a match came from a
   *  curriculum other than their child's. */
  curriculum: string;
  grade: number;
  plainLanguage: string;
  expectedMethods: string[];
  parentMethod: string;
}

export interface MisconceptionView {
  id: string;
  topic: string;
  /** What the wrong working looks like. Fed to the packet prompt as context. */
  signature: string;
  plainName: string;
  repairQuestion: string;
  visualSvg: string | null;
}

export interface PacketView {
  register: RegisterName;
  language: string;
  primer: string;
  methodMatch: MethodMatch;
  hintLadder: string[];
  scripts: Script[];
  lockedAnswer: string;
  isomorphs: string[];
  misconceptionNote: string | null;
}

/**
 * Where a packet actually came from.
 *
 * A degraded response that looks identical to a real one is worse than an
 * error, because the parent acts on it believing we read their worksheet. The
 * provenance travels with the payload so the screen can say so plainly.
 */
export type PacketSource =
  /** Generated by a live model call for this problem. */
  | "live"
  /** A previous live generation for this same problem, reused. */
  | "cache"
  /** The bundled demo packet. Not a reading of anything the parent uploaded. */
  | "fixture"
  /** A saved generic packet for this standard, after the model failed twice. */
  | "generic";

/** Everything `/problem/[id]` needs, in one object. */
export interface PacketBundle {
  problem: ProblemView;
  standard: StandardView | null;
  misconception: MisconceptionView | null;
  packet: PacketView;
  /** Set when the packet came from the demo fixture or a generic fallback. */
  notice: string | null;
  /** Where this packet came from. See PacketSource. */
  source: PacketSource;
  /** True when the verifier could not check the arithmetic at all. */
  verification: "checked" | "unverified" | "not-applicable";
}

export interface MoveView {
  tOffset: number;
  label: MoveLabelName;
  confidence: number;
}

export interface CardView {
  id: string;
  tOffset: number;
  triggerLabel: MoveLabelName;
  text: string;
}
